encoding: utf-8

# SEO相关信息
title: Julian Hawk
description: Julian Hawk's Blog
keywords: Blog
author: Julian Hawk
footerText: '© 2019 J.H'

# 域名配置,生成sitemap会用到，友链也会用到
domainUrl: 'https://juhawk42.github.io'
# 路径配置，静态资源404一般是这里不对
# 直接域名访问设置为'',有如果是user.github.io/blog/访问的话设置为'/blog'
baseUrl: ''

# 菜单
menu:
  - title: HOME
    url: /
  - title: ARCHIVE
    url: /pages/archive.html
  - title: SEARCH
    url: /pages/search.html
  - title: ABOUT
    url: /pages/about.html

# 文章url前缀，固定格式，不要动
permalink: /posts/:year/:month/:day/:title.html

kramdown:
  auto_ids: true
  input: GFM

exclude: ['CNAME', 'README.md', 'build-tool']
